apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: "image-tag"
          ports:
            - containerPort: 8080
          env:
          - name: DATABASE_URL
            value: "postgresql://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable"
          - name: DB_USERNAME
            valueFrom:
              configMapRef:
                name: app-configmap
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-auth
                key: mobee-password
          - name: DB_HOST
            valueFrom:
              configMapRef:
                name: app-configmap
                key: host
          - name: DB_NAME
            valueFrom:
              configMapRef:
                name: app-configmap
                key: dbname