apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: image-tag
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 200Mi
          env:
            - name: DATABASE_URL
              value:
                postgresql://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):5432/$(DB_NAME)?sslmode=disable
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-auth
                  key: mobee-password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: DB_NAME
