name: Pull Request Check
on:
  pull_request  :
    types:
      - opened
      - edited
      - reopened
      - synchronize

    branches:
      - "*"

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: check lint and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --timeout=10m

      - name: build
        run:
          go build main.go